[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core"]

[target.thumbv4t-none-eabi]
runner = "mgba -l 4095"
rustflags = [
  "-Clinker=arm-none-eabi-ld",
  "-Clink-arg=-Tlinker_scripts/mono_boot.ld",
  "--emit=mir",
]
